version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: my_restaurants_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      PGSSLMODE: disable
    ports:
      - "5000:5432"
    volumes:
      - ./up.sql:/docker-entrypoint-initdb.d/1.sql
      - ./triggers.sql:/docker-entrypoint-initdb.d/2.sql

