DROP TABLE IF EXISTS restaurants;

CREATE TABLE restaurants (
  id VARCHAR(50) UNIQUE NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  owner VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  days_open VARCHAR(100)[],
  specialties VARCHAR(255)[],
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id VARCHAR(50) UNIQUE NOT NULL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  owner_of VARCHAR(100)[],
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);